import { Service } from 'typedi';

@Service()
export class UndercoverService {

    private words: Array<string> = [
        'Hache:Tronéonneuse',
        'Mouton:Chévre',
        'Paddle:Surf',
        'Chameau:Dromadaire',
        'Loup:Hyéne',
        'Mouffle:Mitaine',
        'Nesquik:Trésor (Kellogs)',
        'Parapluie:Parasol',
        'Clope:Chicha',
        'Wagon:Voiture',
        'Liane:Corde',
        'Plante:Feuille',
        'Police:Gendarmerie',
        'Cadenas:Serrure',
        'Jul:Naps',
        'Loupe:Lunettes',
        'Mariage:Couple',
        'Potatoes:Frites',
        'Molaire:Incisive',
        'Pomme:Prune',
        'Menthe:Basilic',
        'Youtube:Dailymotion',
        'Bouée:Gilet de Sauvetage',
        'Catamaran:Voilier',
        'Rugby:Football',
        'Sauces:Epices',
        'Dora:Baboush',
        'Electrique:Essence',
        'Otarie:Phoque',
        'Martinique:Guadeloupe',
        'Four:Chauffage',
        'Solary:Eclypsia',
        'Koh Lanta:Pékin Express',
        'Kotei:Kameto',
        'Math:Physique',
        'Téléphone:Tablette',
        'xFrenchies:Pornhub',
        'Sucre:Farine',
        'Piment:Harissa',
        'Mexique:Pérou',
        'Statue:Sculpture',
        'Biére:Limonade',
        'Vodka:Malibu',
        'Jean-Sebastien Bach:Chopin',
        'Ferrari:Porsche',
        'Compétition:Tournoi',
        'Piscine:Jacuzzi',
        'Perrier:Quezac',
        'Thermométre:Suppositoire',
        'Hache:Tronéonneuse',
       ' Mouton:Chévre',
        'Paddle:Surf',
        'Chameau:Dromadaire',
        'Loup:Hyéne',
        'Mouffle:Mitaine',
        'Nesquik:Trésor (Kellogs)',
        'Parapluie:Parasol',
        'Clope:Chicha',
        'Wagon:Voiture',
        'Liane:Corde',
        'Plante:Feuille',
        'Police:Gendarmerie',
        'Cadenas:Serrure',
        'Jul:Naps',
        'Loupe:Lunettes',
        'Mariage:Couple',
        'Potatoes:Frites',
        'Molaire:Incisive',
        'Pomme:Prune',
        'Menthe:Basilic',
        'Youtube:Dailymotion',
        'Bouée:Gilet de Sauvetage',
        'Catamaran:Voilier',
        'Rugby:Football',
        'Sauces:Epices',
        'Dora:Baboush',
        'Electrique:Essence',
        'Otarie:Phoque',
        'Martinique:Guadeloupe',
        'Four:Chauffage',
        'Solary:Eclypsia',
        'Koh Lanta:Pékin Express',
        'Kotei:Kameto',
        'Math:Physique',
        'Téléphone:Tablette',
        'xFrenchies:Pornhub',
        'Sucre:Farine',
        'Piment:Harissa',
        'Mexique:Pérou',
        'Statue:Sculpture',
        'Bière:Limonade',
        'Vodka:Malibu',
        'Jean-Sebastien Bach:Chopin',
        'Ferrari:Porsche',
        'Compétition:Tournoi',
        'Piscine:Jacuzzi',
        'Perrier:Quezac',
        'Thermomètre:Suppositoire'
    ]

    public getWords(quantity: number) {
        return this.words.sort(() => Math.random() - Math.random())
            .slice(0, quantity);
    }
}